Update CONTRIBUTING.md
AccessibleForAll/AccessibleForAll pull request #7
Opened 2023-05-06 19:30 UTC by wasup-yash

Updated Contributing.md file

Motivation for the change:
Closes #3

2023-05-06 20:24 UTC, EmmaDawsonDev requested changes
Thanks so much for your help! There's just a couple of links that need updating to match this repo then this should be ready to merge.

Both the issues ended up in the same PR, it's not a big deal with such small PRs but try to remember to make separate branches for each issue next time.

2023-05-06 20:24 UTC, EmmaDawsonDev commented on CONTRIBUTING.md
> +3.  [Fork](https://github.com/AccessibleForAll/AccessibleWebDev/fork) the project
```suggestion
3.  [Fork](https://github.com/AccessibleForAll/AccessibleForAll/fork) the project
```

2023-05-06 20:24 UTC, EmmaDawsonDev commented on CONTRIBUTING.md
> +    git clone https://github.com/<your-github-username>/AccessibleWebDev
```suggestion
    git clone https://github.com/<your-github-username>/AccessibleForAll
```

2023-05-06 20:24 UTC, EmmaDawsonDev commented on CONTRIBUTING.md
> +    cd AccessibleWebDev
```suggestion
    cd AccessibleForAll
```

2023-05-06 20:24 UTC, EmmaDawsonDev commented on CONTRIBUTING.md
> +    git remote add upstream https://github.com/AccessibleForAll/AccessibleWebDev.git
```suggestion
    git remote add upstream https://github.com/AccessibleForAll/AccessibleForAll.git
```

2023-05-06 20:24 UTC, EmmaDawsonDev commented on CONTRIBUTING.md
> +1.  Look through [Pre-existing issues](https://github.com/AccessibleForAll/AccessibleWebDev/issues) or [Raise a new issue](https://github.com/AccessibleForAll/AccessibleWebDev/issues/new/choose) and
```suggestion
1.  Look through [Pre-existing issues](https://github.com/AccessibleForAll/AccessibleForAll/issues) or [Raise a new issue](https://github.com/AccessibleForAll/AccessibleForAll/issues/new) and ask to be assigned. Pull requests made without a corresponding issue will likely be closed.
```

2023-05-06 20:35 UTC, wasup-yash commented
> Thanks so much for your help! There's just a couple of links that need updating to match this repo then this should be ready to merge.
> 
> Both the issues ended up in the same PR, it's not a big deal with such small PRs but try to remember to make separate branches for each issue next time.

yes, I will update the corrections and also I also realized they same PR will have 2 changes after i created this one, that's why I did a single commit in the main for `appreciation.yml`PR , I will remember it to branch out first while creating, thanks for the review.

2023-05-06 20:39 UTC, EmmaDawsonDev commented
If you want to delete the yaml file from this pr I can merge the other one

2023-05-06 20:50 UTC, wasup-yash commented
> If you want to delete the yaml file from this pr I can merge the other one

yes, Deleted `appreciation.yml`.

2023-05-07 07:57 UTC, EmmaDawsonDev approved these changes
Brilliant, thanks!

2023-05-07 07:57 UTC, merged

2023-05-07 07:58 UTC, wasup-yash commented
> Brilliant, thanks!

thanks for the support, do I need to look up for some other issues too?

2023-05-07 08:58 UTC, EmmaDawsonDev commented
You're more than welcome to look through the current issues or if you find something missing then feel free to create a new issue too. I will hopefully be adding more over time, I just need to start working on a design for this repo so we have something to start with.

2023-05-07 09:02 UTC, wasup-yash commented
> You're more than welcome to look through the current issues or if you find something missing then feel free to create a new issue too. I will hopefully be adding more over time, I just need to start working on a design for this repo so we have something to start with.

that's awesome, I would truly like to work on it, looking forward to more contributions.